// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr_KncNJ7awiSRHzMOlStDs2pp1uKmJWw',
    appId: '1:1023070192441:web:0518a3f4e8c59074549ee8',
    messagingSenderId: '1023070192441',
    projectId: 'studyflow-mit-2026-df982',
    authDomain: 'studyflow-mit-2026-df982.firebaseapp.com',
    storageBucket: 'studyflow-mit-2026-df982.firebasestorage.app',
    measurementId: 'G-5WFJZ53NE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-61cRVFHpguv5xW8PKts0FI_EbN4Glzk',
    appId: '1:1023070192441:android:0bc42aca1284c46f549ee8',
    messagingSenderId: '1023070192441',
    projectId: 'studyflow-mit-2026-df982',
    storageBucket: 'studyflow-mit-2026-df982.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF1kOQ-3UNFC2ZldDPaaS1YUUScNdhj7I',
    appId: '1:1023070192441:ios:e2eaae4ad1e8a8b7549ee8',
    messagingSenderId: '1023070192441',
    projectId: 'studyflow-mit-2026-df982',
    storageBucket: 'studyflow-mit-2026-df982.firebasestorage.app',
    iosBundleId: 'com.example.studyflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF1kOQ-3UNFC2ZldDPaaS1YUUScNdhj7I',
    appId: '1:1023070192441:ios:e2eaae4ad1e8a8b7549ee8',
    messagingSenderId: '1023070192441',
    projectId: 'studyflow-mit-2026-df982',
    storageBucket: 'studyflow-mit-2026-df982.firebasestorage.app',
    iosBundleId: 'com.example.studyflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr_KncNJ7awiSRHzMOlStDs2pp1uKmJWw',
    appId: '1:1023070192441:web:69b123f4676b4197549ee8',
    messagingSenderId: '1023070192441',
    projectId: 'studyflow-mit-2026-df982',
    authDomain: 'studyflow-mit-2026-df982.firebaseapp.com',
    storageBucket: 'studyflow-mit-2026-df982.firebasestorage.app',
    measurementId: 'G-TH4P53K6B7',
  );
}
